name: teco-challenge-actions
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  code-quality:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        run: cd backend && npm i

      - name: Run backend linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: './backend'

      - name: Install web dependencies
        run: cd web && npm i

      - name: Run web linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: './web'
