name: CT
on: 
  pull_request: 
    branches:
      - main
    paths:
      - 'backend/**'
      
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: lccoornel/codeeducation:latest
    steps:
      name: run image
      run: docker run lccoornel/codeeducation:latest
