version: '3'

volumes:
  node-modules-web:

services:
  web:
    build:
      context: .
      target: prod
    container_name: web
    volumes: 
      - node-modules-web:/usr/app/node_modules
    expose: 
      - "4173"
    environment:
      NODE_ENV: ${NODE_ENV:-prod}